/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.models.ViewModel;
import org.example.services.ViewService;

import javafx.geometry.Point2D;
import com.sun.prism.paint.Paint;

import org.example.entities.Player;
import org.example.enums.Direction;

import java.util.Arrays;

import org.example.controllers.ViewController;

import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.image.PixelFormat;
import javafx.scene.image.PixelWriter;
import javafx.scene.image.WritableImage;
import javafx.scene.input.KeyCode;
import javafx.scene.layout.StackPane;
import org.example.assets.Texture;
import javafx.scene.paint.Color;
import javafx.scene.robot.Robot;
import javafx.stage.Screen;
import javafx.stage.Stage;
import org.example.utils.Loader;
import org.example.assets.TextureRegistry;

public class App extends Application{

  static final int WIDTH = 640;
  static final int HEIGHT = 480;
  private boolean isProgramaticMouseMovement = false;
  private boolean mouseCaptured = false;
  private int[] pixelArray = new int[WIDTH * HEIGHT];
  private WritableImage screenBuffer = new WritableImage(WIDTH, HEIGHT);
  private PixelWriter pixelWriter = screenBuffer.getPixelWriter();
  @Override
  public void start(Stage stage){
    int[][] wallTex = {{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},
                          {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1},}; 

    int[][] vertTexture = {{0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1},
                           {0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1}};
    Loader.loadTextures(wallTex);
    ViewModel vModel = new ViewModel(new Player(3,6));
    ViewController vController = new ViewController(vModel);
  
    Canvas canvas = new Canvas(WIDTH, HEIGHT);
    GraphicsContext gc = canvas.getGraphicsContext2D();

    StackPane root = new StackPane(canvas);
    Scene scene = new Scene(root, WIDTH, HEIGHT);

    scene.setOnMouseClicked(event -> {
      if (!mouseCaptured){
        isProgramaticMouseMovement = true;
        Point2D screenCenter = scene.getRoot().localToScreen(scene.getWidth()/2,scene.getHeight()/2);
        double sceneX = scene.getWindow().getX(); double sceneY = scene.getWindow().getY();
        System.out.println("X: " + (sceneX + screenCenter.getX()) + " Y: " + (sceneY + screenCenter.getY()));
        try{
          new Robot().mouseMove((int)Math.round(screenCenter.getX()), (int)Math.round(screenCenter.getY()));
          isProgramaticMouseMovement = true;
          mouseCaptured = true;

        } catch (Exception e){
          e.printStackTrace();
        }
        System.out.println("Mouse: Captured");

      }
    });
    //TODO: Stop creating new robot each frame, instantiate a robot as a instance variable and reuse. 
    scene.setOnMouseMoved(event -> {
      if (isProgramaticMouseMovement){
        isProgramaticMouseMovement = false;
        return;
      }
      if (mouseCaptured){
        //Grabbing the current monitors output scale 
        Screen screen = Screen.getScreensForRectangle(stage.getX(), stage.getY(), 1, 1).get(0);
        double mouseX = event.getScreenX();
        Point2D sceneCenter = canvas.localToScreen(canvas.getWidth()/2, canvas.getHeight()/2);
        double mouseDeltaX = (mouseX - sceneCenter.getX());

        //Ignoring any deltas that are less than the output scale, this prevents the gittery rotations.
        if (Math.abs(mouseDeltaX) <= screen.getOutputScaleX()){
          return;
        }
        //Rounding the delta value, this gives consistent delta values across different monitors.
        vController.rotate(Math.round(mouseDeltaX));
        
        
        //Moving the cursor back to the center of the game window. 
        try{
          new Robot().mouseMove((int)Math.round(sceneCenter.getX()), (int)Math.round(sceneCenter.getY()));
          isProgramaticMouseMovement = true;

        } catch (Exception e){
          e.printStackTrace();
        }
      }
    });


    scene.setOnKeyPressed(event -> {
      KeyCode code = event.getCode();
      //Appending movement enums to a buffer when a key is pressed.
      switch(code){
        case KeyCode.W:
          vController.appendMovement(Direction.FORWARD); 
        break;

        case KeyCode.S:
          vController.appendMovement(Direction.BACKWARD); 
        break;

        case KeyCode.A:
          vController.appendMovement(Direction.LEFT);
        break;

        case KeyCode.D:
          vController.appendMovement(Direction.RIGHT);
        break;

        case KeyCode.X:
          mouseCaptured = false;
        break;

        default:
          break;
      }
    });

    //Removing movement enums from buffer when a key is released.
    scene.setOnKeyReleased(event -> {
      KeyCode code = event.getCode();
      switch(code){
        case KeyCode.W:
          vController.removeMovement(Direction.FORWARD);
        break;

        case KeyCode.S:
          vController.removeMovement(Direction.BACKWARD);
        break;

        case KeyCode.D:
          vController.removeMovement(Direction.RIGHT);
        break;

        case KeyCode.A:
          vController.removeMovement(Direction.LEFT);
        break;
        
        default:
        break;
      }
    });


    stage.setTitle("Raycaster");
    stage.setScene(scene);
    stage.show();
    Point2D center = scene.getRoot().localToScreen(scene.getWidth()/2,scene.getHeight()/2);

    // Initial clear
    gc.clearRect(0, 0, WIDTH, HEIGHT);
    Player player = vModel.getPlayer();

    new AnimationTimer(){
      @Override
      public void handle(long now){
        vController.move();
        gc.clearRect(0,0,WIDTH,HEIGHT);
        Arrays.fill(pixelArray, 0xFFEAEAEA);
        for (int i = 0; i < WIDTH; i++){
          int color = 0;
          double[] sliceData = vController.calculateColumn(i);

          double step = 32.0/sliceData[4]; //1.0 * textureHeight/wallheight.
          //Calculating the raw uncapped top bound of the wall. 
          int rawTop = (int)((HEIGHT - sliceData[4])/2.0);
          //The x or column of the texture we need to use.
          double wallHeight = sliceData[4];
          //Clamping the top and lower bound of the wall slice to the screen boundaries.
          int drawStart = (int)((-wallHeight/2) + (HEIGHT/2));
          int drawEnd = (int)((wallHeight/2) + (HEIGHT/2));
          if (drawStart < 0){drawStart = 0;};
          if (drawEnd >= HEIGHT){drawEnd = HEIGHT - 1;}

          int screenX = i;
          if (screenX < 0 || screenX >= WIDTH) continue;

          //Extract the absolute textrue x index 
          int texX = (int)Math.floor(sliceData[5] * 32.0);

          //clean wrapping loop for texture coordinate. 
          texX = texX %32;
          if (texX < 0) {
            texX += 32;
          }
          if (texX < 0) texX = 0;
          if (texX > 31) texX = 31;

          //calculate the starting texture vertical position.
          double texPos = (drawStart - rawTop) * step;

          //Loop to grab the texture color values and write them to the pixel buffer.
          for (int j = drawStart; j <= drawEnd; j++){
            //Caclulating the Y index of the texture array we need to use, and ensuring it stays within the valid bounds of the array.
            int texY = (int)texPos;
            if (texY > 31) {texY = 31;};
            if (texY < 0) {texY = 0;};

            color = TextureRegistry.getPixel(1, texY, texX).getValue();

            //apply shading
            if (sliceData[0] == 1){
              color = ViewService.applyShading(color);
            }
            pixelArray[(j * WIDTH) + screenX] = color;
            texPos += step;
          }
        }
        pixelWriter.setPixels(0,0, WIDTH, HEIGHT, PixelFormat.getIntArgbInstance(), pixelArray, 0, WIDTH);
        gc.drawImage(screenBuffer, 0, 0);
      }
    }.start();
  }

  public static void main(String[] args) {
    launch(args);
  }
}
