/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.models.ViewModel;
import org.example.entities.Player;
import org.example.controllers.ViewController;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application{

  static final int WIDTH = 640;
  static final int HEIGHT = 480;

  @Override
  public void start(Stage stage){
    ViewModel vModel = new ViewModel(new Player(3,6));
    ViewController vController = new ViewController(vModel);
    Canvas canvas = new Canvas(WIDTH, HEIGHT);
    GraphicsContext gc = canvas.getGraphicsContext2D();

    StackPane root = new StackPane(canvas);
    Scene scene = new Scene(root, WIDTH, HEIGHT);

    stage.setTitle("Raycaster");
    stage.setScene(scene);
    stage.show();

    // Initial clear
    gc.clearRect(0, 0, WIDTH, HEIGHT);
    Player player = vModel.getPlayer();
    System.out.println(player.getPosX() + " " + player.getPosY() + " " + player.getHeading());
    //TODO: Put all logic below inside a controller method so we can iterate over an array of rays 
    //TODO:and have the below data returned here so we can draw each slice in order left to right.
    
    for (int i = 0; i < 60; i++){
      double[] sliceData = vController.calculateColumn(i);
      gc.fillRect(sliceData[0],sliceData[1],sliceData[2],sliceData[3]);//drawing the slice
    }
  }

  public static void main(String[] args) {
    launch(args);
  }
}
